version: "3"
services:
  playwright:
    build: .
    volumes:
      - ../:/work
      - .zsh_history:/root/.zsh_history
      - /tmp/.X11-unix:/tmp/.X11-unix
    working_dir: /work
    environment:
      TZ: Asia/Tokyo
      DISPLAY: :0
    tty: true
